// File: src/api/routes/event.routes.ts
import { Router, Request, Response, NextFunction } from 'express';
import { EventService } from '../../services/event.service.js';
import { SSEManager } from '../../realtime/sse.js';
import { validateRequest } from '../middleware/validate.js';
import { eventQuerySchema, projectIdParamsSchema } from '../schemas.js';

const MAX_LAST_EVENT_ID_LENGTH = 128;
const LAST_EVENT_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/;

/**
 * Event IDs generated by EventService are URL-safe ULIDs. Keep the accepted
 * cursor bounded and reject control/whitespace characters before querying the
 * database; malformed cursors intentionally reset to the live tail rather
 * than causing an EventSource reconnect loop.
 */
export function parseLastEventId(value: string | undefined): string | null {
  if (!value || value.length > MAX_LAST_EVENT_ID_LENGTH || !LAST_EVENT_ID_PATTERN.test(value)) {
    return null;
  }
  return value;
}

/**
 * Express resolves `req.ip` from the socket peer unless that peer is in the
 * deployment's explicit trust-proxy allowlist. Direct spoofed forwarding
 * headers remain inert, while the fixed Caddy edge can supply the real client
 * address instead of collapsing every proxied stream into one IP bucket.
 */
export function getTrustedSSEClientIp(req: Request): string | null {
  return req.ip || req.socket.remoteAddress || null;
}

export function createEventRouter(eventService: EventService, sseManager: SSEManager): Router {
  const router = Router();

  router.get('/projects/:projectId/events', ...validateRequest({ query: eventQuerySchema, params: projectIdParamsSchema }), async (req: Request, res: Response, next: NextFunction) => {
    try {
      const events = await eventService.listPage(req.params.projectId, {
        entity_type: req.query.entity_type as string,
        entity_id: req.query.entity_id as string,
        since: req.query.since as string,
      }, {
        cursor: req.query.cursor as string | undefined,
        limit: req.query.limit as number | undefined,
      });
      res.json(events);
    } catch (err) {
      next(err);
    }
  });

  router.get('/projects/:projectId/events/stream', ...validateRequest({ params: projectIdParamsSchema }), async (req: Request, res: Response, next: NextFunction) => {
    try {
      const auth = req.authContext;
      const workspaceId = await eventService.getProjectWorkspaceId(req.params.projectId);
      const lastEventId = parseLastEventId(req.get('Last-Event-ID'));

      // Permission middleware establishes membership, but it cannot know
      // which project identifier is being streamed. Refuse a project from a
      // different workspace without confirming that it exists.
      if (auth?.is_workspace_member && (!auth.workspace_id || auth.workspace_id !== workspaceId)) {
        res.status(404).json({ error: 'not_found', message: 'Project not found.' });
        return;
      }

      const clientId = `client_${Date.now()}_${Math.random().toString(36).substring(7)}`;
      const result = sseManager.addClient(req.params.projectId, clientId, res, {
        principalId: auth?.principal?.id,
        ip: getTrustedSSEClientIp(req),
        workspaceId,
      }, { replaying: lastEventId !== null });
      if (!result.accepted) {
        res.setHeader('Retry-After', result.retryAfterSeconds.toString());
        res.status(429).json({
          error: 'sse_capacity_exceeded',
          message: 'SSE connection limit reached. Retry later.',
          scope: result.scope,
          retry_after_seconds: result.retryAfterSeconds,
        });
        return;
      }

      if (lastEventId !== null) {
        try {
          // EventService performs a project-scoped cursor lookup and caps the
          // returned tail. Unknown/foreign/stale cursors produce no replay,
          // while the client still receives new events after this point.
          const resume = await eventService.listAfterId(
            req.params.projectId,
            lastEventId,
            100,
          );
          sseManager.completeReplay(clientId, resume.events);
        } catch (err) {
          sseManager.removeClient(clientId);
          if (res.headersSent) {
            res.end();
            return;
          }
          next(err);
        }
      }
    } catch (err) {
      next(err);
    }
  });

  return router;
}
